### ISSUE TITLE
Complete the draft template for section 2.1.6-2.4

### ISSUE THREAD

**Issue by Ghost-8D** [CS-UCY-EPL343/EPL343.Winter18.Team5#14]
Download the draft from the Moodle and complete the section based on what we know so far. If there are any blank points, contact me. This must be done and uploaded to the repository by Monday, Oct 01 (23.59:59).

**Comment by adamos2468** [comment]
2.1.6 - The amount of RAM needed should be around maximum 256Mb and storage at most 512Mb.
2.1.7 - Because it's an android aplication the only thing needed is play store to download the app.
2.2 - The app will be used by fliers and can have different educational levels. But expirenced because they can fly after training.
2.3 - There are a lot of constraints. Because the use will be mainly mid air the interface should be very easy to see and use to avoid any accidents. Also for voice commands we should consider the wind in order to not have any noise in the commands.
2.4 - Because we need a lot of data to make the product as usable as possible after some testings and feedbacks. May be a lot of changes.
