### ISSUE TITLE
Q. Part2: Adamos.

### ISSUE THREAD

**Issue by Ghost-8D** [CS-UCY-EPL343/EPL343.Winter18.Team5#3]
Prepare some questions for section 2.1.4-2.1.7

**Comment by adamos2468** [comment]
The questions asked to be prepared:
2.1.4- What are the required software products we will need? (E.q. Operating System and DBMS)
2.1.5- What are the interfaces of communication? (E.q. Local Network, Internet)
2.1.6- What are the Memory Constraints for this project?
2.1.7- What is the process of installation in order to run the software?
